spring:
  application:
    name: htmxdemo

  # Database Configuration
  datasource:
    url: ${HTMX_DB_URL}
    username: ${HTMX_DB_USERNAME}
    password: ${HTMX_DB_PASSWORD}
    hikari:
      maximum-pool-size: 4  # Keep low for Free Tier RAM
      minimum-idle: 1

  # Mail Configuration (Moved here for proper Auto-Configuration)
  mail:
    host: smtp.gmail.com
    port: 587
    username: amanueltemesgen360@gmail.com
    password: ${GMAIL_APP_PASSWORD} # Use your .env file via java-dotenv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    open-in-view: false      # Performance: closes connections faster
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    banner-mode: "off"

# Logging Strategy
logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{15} : %m%n"
  level:
    root: WARN
    com.aman: INFO
    org.springframework: WARN
    org.hibernate.SQL: ERROR