spring:
  application:
    name: htmxdemo

  datasource:
    url: ${HTMX_DB_URL}
    username: ${HTMX_DB_USERNAME}
    password: ${HTMX_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
